[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./broadcast/" },
]
via_ir = true
optimizer = true
optimizer_runs = 200